server:
  port: 8101

spring:
  application:
    name: CMS Student Payment

  datasource:
    url: jdbc:mysql://localhost:3306/cms_payment
    username: root
    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto=update: update

