server:
  port: 8101
  servlet:
    context-path: /payment

spring:
  application:
    name: CMS-Student-Payment

  datasource:
    url: jdbc:mysql://bade90e09555e2:d1873f8e@us-cdbr-east-06.cleardb.net/heroku_80aa2644224a030?reconnect=true
#    username: root
#    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
  instance:
    preferIpAddress: true

student:
  uri:
    baseUrl: https://cms-student.herokuapp.com/
    getStudentById: student/api/v1/student/##STUDENT-ID##
    getAllStudentDetails: student/api/v1/student

location:
  uri:
    baseUrl: https://cms-location.herokuapp.com/
    getAllLocationDetails: tuition/api/v1/tuition/

security:
  key: accessKey
