server:
  port: 8101
  servlet:
    context-path: /payment

spring:
  application:
    name: CMS-Student-Payment
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/cms_payment
    username: root
    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

student:
  uri:
    baseUrl: http://localhost:8104/
    getStudentById: student/api/v1/student/##STUDENT-ID##
    getAllStudentDetails: student/api/v1/student

location:
  uri:
    baseUrl: http://localhost:8105/
    getAllLocationDetails: tuition/api/v1/tuition/

security:
  key: accessKey


logging:
  level:
    com.cms.payment: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:./log}

